spring:
  application:
    name: Mimo Games
  datasource:
    url: ${MIMO_DB_URL:jdbc:mysql://localhost:3306/mimo_games?createDatabaseIfNotExist=true}
    username: ${MIMO_DB_USER:root}
    password: ${MIMO_DB_PASSWORD:password}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      id.db_structure_naming_strategy: legacy
  sql:
    init:
      mode: always

logging:
  level:
    edu.sorbonne: DEBUG

